Gem::Specification.new do |s|
  s.name              = %q{refinerycms-news}
  s.version           = %q{2.0.0}
  s.description       = %q{A really straightforward open source Ruby on Rails news engine designed for integration with RefineryCMS.}
  s.date              = %q{2012-02-17}
  s.summary           = %q{Ruby on Rails news engine for RefineryCMS.}
  s.email             = %q{info@refinerycms.com}
  s.homepage          = %q{http://refinerycms.com}
  s.authors           = %w(Resolve\ Digital)
  s.require_paths     = %w(lib)

  s.add_dependency    'refinerycms-core', '~> 2.0.0'

  s.files             = [
    'app',
    'app/controllers',
    'app/controllers/refinery',
    'app/controllers/refinery/news',
    'app/controllers/refinery/news/admin',
    'app/controllers/refinery/news/admin/items_controller.rb',
    'app/controllers/refinery/news/items_controller.rb',
    'app/helpers',
    'app/helpers/refinery',
    'app/helpers/refinery/news',
    'app/helpers/refinery/news/items_helper.rb',
    'app/models',
    'app/models/refinery',
    'app/models/refinery/news',
    'app/models/refinery/news/item.rb',
    'app/views',
    'app/views/refinery',
    'app/views/refinery/news',
    'app/views/refinery/news/admin',
    'app/views/refinery/news/admin/items',
    'app/views/refinery/news/admin/items/_form.html.erb',
    'app/views/refinery/news/admin/items/_item.html.erb',
    'app/views/refinery/news/admin/items/_locale_picker.html.erb',
    'app/views/refinery/news/admin/items/edit.html.erb',
    'app/views/refinery/news/admin/items/index.html.erb',
    'app/views/refinery/news/admin/items/new.html.erb',
    'app/views/refinery/news/items',
    'app/views/refinery/news/items/_recent_posts.html.erb',
    'app/views/refinery/news/items/archive.html.erb',
    'app/views/refinery/news/items/index.html.erb',
    'app/views/refinery/news/items/index.rss.builder',
    'app/views/refinery/news/items/show.html.erb',
    'app/views/refinery/news/items/widgets',
    'app/views/refinery/news/items/widgets/_news_archive.html.erb',
    'app/views/refinery/news/shared',
    'app/views/refinery/news/shared/_body_content_right.html.erb',
    'app/views/refinery/news/shared/_item.html.erb',
    'config',
    'config/locales',
    'config/locales/bg.yml',
    'config/locales/cs.yml',
    'config/locales/de.yml',
    'config/locales/en.yml',
    'config/locales/es-MX.yml',
    'config/locales/es.yml',
    'config/locales/fr.yml',
    'config/locales/it.yml',
    'config/locales/jp.yml',
    'config/locales/lv.yml',
    'config/locales/nb.yml',
    'config/locales/nl.yml',
    'config/locales/pl.yml',
    'config/locales/pt-BR.yml',
    'config/locales/ru.yml',
    'config/locales/sk.yml',
    'config/locales/sl.yml',
    'config/locales/zh-CN.yml',
    'config/locales/zh-TW.yml',
    'config/routes.rb',
    'db',
    'db/migrate',
    'db/migrate/20110817203701_create_news_items.rb',
    'db/migrate/20110817203702_add_external_url_to_news_items.rb',
    'db/migrate/20110817203703_translate_news_items.rb',
    'db/migrate/20110817203704_add_image_id_to_news_items.rb',
    'db/migrate/20110817203705_add_expiration_date_to_news_items.rb',
    'db/migrate/20110817203706_remove_image_id_and_external_url_from_news.rb',
    'db/migrate/20120129230838_add_source_to_news_items.rb',
    'db/migrate/20120129230839_translate_source.rb',
    'db/seeds.rb',
    'Gemfile',
    'lib',
    'lib/gemspec.rb',
    'lib/generators',
    'lib/generators/refinery',
    'lib/generators/refinery/news_generator.rb',
    'lib/refinery',
    'lib/refinery/news',
    'lib/refinery/news/engine.rb',
    'lib/refinery/news/version.rb',
    'lib/refinery/news.rb',
    'lib/refinerycms-news.rb',
    'license.md',
    'Rakefile',
    'readme.md',
    'spec',
    'spec/models',
    'spec/models/refinery',
    'spec/models/refinery/news',
    'spec/models/refinery/news/item_spec.rb',
    'spec/requests',
    'spec/requests/manage_news_items_spec.rb',
    'spec/requests/news_archive.rb',
    'spec/requests/visit_news_items_spec.rb',
    'spec/spec_helper.rb',
    'spec/support',
    'spec/support/refinery',
    'spec/support/refinery/factories.rb',
    'tasks',
    'tasks/rspec.rake'
  ]
end
